name: Build ARM Binary

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install cross-compilation dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
    
    - name: Build for ARM64
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: arm64
        CC: aarch64-linux-gnu-gcc
      run: |
        go build -o piheat-arm64 .
        
    - name: Build for ARM (32-bit)
      env:
        CGO_ENABLED: 1
        GOOS: linux
        GOARCH: arm
        GOARM: 7
        CC: arm-linux-gnueabihf-gcc
      run: |
        go build -o piheat-arm .
    
    - name: Upload ARM64 artifact
      uses: actions/upload-artifact@v4
      with:
        name: piheat-arm64
        path: piheat-arm64
        
    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        name: piheat-arm
        path: piheat-arm
        
    - name: Release binaries
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          piheat-arm64
          piheat-arm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}